apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: tylerlaporte-com-tls
spec:
    secretName: tylerlaporte-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: tylerlaporte.com
    dnsName:
        - tylerlaporte.com
        - www.tylerlaporte.com
    acme:
        config:
            - http01:
                ingressClass: nginx
            domains:
                - tylerlaporte.com
                - www.tylerlaporte.com
